import crypto from "node:crypto";
import { lstat, mkdir, open, readFile, readdir, realpath, rename, unlink } from "node:fs/promises";
import path from "node:path";
import { canonicalJsonBuffer } from "../../result-bundle/canonical-json.js";
import { WebBridgeError, WEB_BRIDGE_PROTOCOL_VERSION, contentDigest, type BridgeJobIdentity } from "../contracts.js";
import type { AuthoringJobRequest } from "../web-bridge.js";
import type { FinalReviewRequest } from "../contracts.js";
import { DEFAULT_RELAY_LIMITS, type RelayJobKind, type RelayJobRecord, type RelayLimits, type RelayStoredEvent } from "./protocol.js";

function safeId(value: string): void { if (!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value)) throw new WebBridgeError("RELAY_ID_INVALID", "Relay identifier is invalid."); }
export class RelayFileStore {
  private readonly limits: RelayLimits;
  private queue: Promise<void> = Promise.resolve();
  constructor(private readonly root: string, limits: Partial<RelayLimits> = {}, private readonly now: () => Date = () => new Date()) { this.limits = { ...DEFAULT_RELAY_LIMITS, ...limits }; }
  private async safeRoot(): Promise<string> { const absolute = path.resolve(this.root); await mkdir(absolute, { recursive: true, mode: 0o700 }); const stat = await lstat(absolute); if (!stat.isDirectory() || stat.isSymbolicLink() || await realpath(absolute) !== absolute) throw new WebBridgeError("RELAY_STORE_ROOT_UNSAFE", "Relay store root is not canonical."); return absolute; }
  private async locked<T>(operation: () => Promise<T>): Promise<T> { const previous = this.queue; let release!: () => void; this.queue = new Promise<void>((resolve) => { release = resolve; }); await previous; try { return await operation(); } finally { release(); } }
  private async read(jobId: string): Promise<RelayJobRecord> { safeId(jobId); const bytes = await readFile(path.join(await this.safeRoot(), `${jobId}.json`)); if (bytes.byteLength > this.limits.maximum_record_bytes) throw new WebBridgeError("RELAY_RECORD_LIMIT", "Relay record exceeds its bound."); const record = JSON.parse(bytes.toString("utf8")) as RelayJobRecord; if (record.identity.job_id !== jobId || record.schema_version !== "1.0" || !Array.isArray(record.events)) throw new WebBridgeError("RELAY_RECORD_INVALID", "Relay record failed identity validation."); return record; }
  private async write(record: RelayJobRecord): Promise<void> { const bytes = canonicalJsonBuffer(record); if (bytes.byteLength > this.limits.maximum_record_bytes) throw new WebBridgeError("RELAY_RECORD_LIMIT", "Relay record exceeds its bound."); const root = await this.safeRoot(); const target = path.join(root, `${record.identity.job_id}.json`); const temp = `${target}.tmp-${process.pid}-${crypto.randomUUID()}`; const handle = await open(temp, "wx", 0o600); try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); } try { await rename(temp, target); } finally { await unlink(temp).catch(() => undefined); } }
  async create(kind: RelayJobKind, owner: string, request: AuthoringJobRequest | FinalReviewRequest, idempotencyKey: string, ttlSeconds: number): Promise<BridgeJobIdentity> { safeId(owner); safeId(idempotencyKey); if (!Number.isSafeInteger(ttlSeconds) || ttlSeconds < 60 || ttlSeconds > this.limits.maximum_ttl_seconds) throw new WebBridgeError("RELAY_TTL_INVALID", "Relay TTL is outside its bound."); return await this.locked(async () => { const requestDigest = contentDigest({ kind, owner, request }); const existing = await this.findByIdempotency(owner, idempotencyKey); if (existing) { if (existing.identity.content_sha256 !== requestDigest) throw new WebBridgeError("RELAY_IDEMPOTENCY_CONFLICT", "Conflicting relay creation replay was rejected."); if (Date.parse(existing.identity.expires_at) <= this.now().getTime()) throw new WebBridgeError("RELAY_JOB_EXPIRED", "The idempotent relay job has expired; create a new local session."); return existing.identity; } const active = await this.list(owner); if (active.filter((item) => Date.parse(item.identity.expires_at) > this.now().getTime()).length >= this.limits.maximum_active_jobs_per_owner) throw new WebBridgeError("RELAY_ACTIVE_JOB_LIMIT", "Active relay job limit reached."); const created = this.now(); const jobId = `${kind === "authoring" ? "job" : "review"}-${contentDigest({ owner, idempotencyKey, request }).slice(0, 24)}`; const identity: BridgeJobIdentity = { protocol_version: WEB_BRIDGE_PROTOCOL_VERSION, job_id: jobId, owner, created_at: created.toISOString(), expires_at: new Date(created.getTime() + ttlSeconds * 1000).toISOString(), content_sha256: requestDigest }; const record: RelayJobRecord = { schema_version: "1.0", identity, kind, request, events: [], idempotency: { [`create:${idempotencyKey}`]: requestDigest } }; await this.write(record); return identity; }); }
  async append(jobId: string, owner: string, type: string, payload: unknown, idempotencyKey: string): Promise<RelayStoredEvent> { safeId(idempotencyKey); return await this.locked(async () => { const record = await this.read(jobId); this.authorize(record, owner); const digest = contentDigest({ type, payload }); const previous = record.idempotency[`event:${idempotencyKey}`]; if (previous) { if (previous !== digest) throw new WebBridgeError("RELAY_IDEMPOTENCY_CONFLICT", "Conflicting relay mutation replay was rejected."); const event = record.events.find((value) => value.idempotency_key === idempotencyKey); if (!event) throw new WebBridgeError("RELAY_RECORD_INVALID", "Relay idempotency index is inconsistent."); return event; } if (record.events.length >= this.limits.maximum_events_per_job) throw new WebBridgeError("RELAY_EVENT_LIMIT", "Relay event limit reached."); const event: RelayStoredEvent = { sequence: (record.events.at(-1)?.sequence ?? 0) + 1, type, payload, created_at: this.now().toISOString(), idempotency_key: idempotencyKey, content_sha256: digest }; record.events.push(event); record.idempotency[`event:${idempotencyKey}`] = digest; await this.write(record); return event; }); }
  async get(jobId: string, owner: string): Promise<RelayJobRecord> { const record = await this.read(jobId); this.authorize(record, owner); return record; }
  async events(jobId: string, owner: string, afterSequence: number): Promise<RelayStoredEvent[]> { const record = await this.get(jobId, owner); return record.events.filter((event) => event.sequence > afterSequence); }
  async list(owner: string): Promise<RelayJobRecord[]> { const root = await this.safeRoot(); const names = (await readdir(root)).filter((name) => /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}\.json$/.test(name)); if (names.length > this.limits.maximum_active_jobs_per_owner * 4) throw new WebBridgeError("RELAY_RECORD_LIMIT", "Relay store record count exceeds its bound."); const values: RelayJobRecord[] = []; for (const name of names) { const record = await this.read(name.slice(0, -5)); if (record.identity.owner === owner) values.push(record); } return values.sort((a, b) => a.identity.created_at.localeCompare(b.identity.created_at)); }
  private async findByIdempotency(owner: string, key: string): Promise<RelayJobRecord | undefined> { return (await this.list(owner)).find((record) => `create:${key}` in record.idempotency); }
  private authorize(record: RelayJobRecord, owner: string): void { if (record.identity.owner !== owner) throw new WebBridgeError("RELAY_FORBIDDEN", "Relay job ownership check failed."); if (Date.parse(record.identity.expires_at) <= this.now().getTime()) throw new WebBridgeError("RELAY_JOB_EXPIRED", "Relay job has expired."); }
}
