import http, { type IncomingMessage, type ServerResponse } from "node:http";
import { WebBridgeError, parseWebContractEnvelope, parseWebImplementationSubmission, parseWebVerdictEnvelope } from "../contracts.js";
import { RelayFileStore } from "./file-store.js";
import { PersonalBearerAuthenticator } from "./auth.js";
import { toAuthoringEvent } from "./protocol.js";

const MAX_REQUEST_BYTES = 8_388_608;
async function jsonBody(request: IncomingMessage): Promise<unknown> { const chunks: Buffer[] = []; let bytes = 0; for await (const raw of request) { const chunk = Buffer.from(raw); bytes += chunk.length; if (bytes > MAX_REQUEST_BYTES) throw new WebBridgeError("RELAY_REQUEST_LIMIT", "Relay request exceeded its byte bound."); chunks.push(chunk); } try { return JSON.parse(Buffer.concat(chunks).toString("utf8")); } catch { throw new WebBridgeError("RELAY_REQUEST_INVALID", "Relay request is not valid JSON."); } }
function send(response: ServerResponse, status: number, value: unknown): void { const body = Buffer.from(JSON.stringify(value)); response.writeHead(status, { "Content-Type": "application/json", "Content-Length": body.length, "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" }); response.end(body); }
function idempotency(request: IncomingMessage): string { const value = request.headers["idempotency-key"]; if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value)) throw new WebBridgeError("RELAY_IDEMPOTENCY_REQUIRED", "A valid Idempotency-Key is required."); return value; }

export function createRelayServer(options: { store: RelayFileStore; authenticator: PersonalBearerAuthenticator }): http.Server {
  return http.createServer(async (request, response) => {
    try {
      const principal = options.authenticator.authenticate(request.headers.authorization);
      const url = new URL(request.url ?? "/", "http://relay.invalid");
      const method = request.method ?? "GET";
      if (method === "GET" && url.pathname === "/v1/status") { const jobs = await options.store.list(principal.owner); send(response, 200, { configured: true, connected: true, account: principal.owner, pending_author_job: jobs.find((job) => job.kind === "authoring")?.identity.job_id, pending_final_review: jobs.find((job) => job.kind === "final_review")?.identity.job_id }); return; }
      if (method === "POST" && url.pathname === "/v1/authoring/jobs") { const supplied = await jsonBody(request) as any; const body = supplied && typeof supplied === "object" && !Array.isArray(supplied) ? { ...supplied, owner: principal.owner } : supplied; const identity = await options.store.create("authoring", principal.owner, body, idempotency(request), body?.ttl_seconds); send(response, 201, identity); return; }
      if (method === "POST" && url.pathname === "/v1/final-reviews") { const body = await jsonBody(request) as any; const identity = await options.store.create("final_review", principal.owner, body, idempotency(request), 86_400); send(response, 201, identity); return; }
      if (method === "GET" && url.pathname === "/v1/authoring/pending") { const record = (await options.store.list(principal.owner)).find((job) => job.kind === "authoring"); send(response, 200, { job: record ? { identity: record.identity, request: record.request } : null }); return; }
      if (method === "GET" && url.pathname === "/v1/final-reviews/pending") { const record = (await options.store.list(principal.owner)).find((job) => job.kind === "final_review"); send(response, 200, { review: record ? { identity: record.identity, request: record.request } : null }); return; }
      const eventMatch = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/events$/);
      if (method === "GET" && eventMatch) { const after = Number(url.searchParams.get("after") ?? 0); if (!Number.isSafeInteger(after) || after < 0) throw new WebBridgeError("RELAY_REQUEST_INVALID", "Event sequence is invalid."); const event = (await options.store.events(decodeURIComponent(eventMatch[1]!), principal.owner, after)).find((item) => ["repository_command_result", "user_clarification"].includes(item.type)) ?? null; send(response, 200, { event }); return; }
      if (method === "POST" && eventMatch) { const body = await jsonBody(request) as { type?: unknown; payload?: unknown }; if (typeof body.type !== "string" || !["repository_command", "contract_sealed", "implementation_sealed"].includes(body.type)) throw new WebBridgeError("RELAY_EVENT_INVALID", "Authoring event type is invalid."); let payload = body.payload; if (body.type === "contract_sealed") payload = { envelope: parseWebContractEnvelope((body.payload as any)?.envelope ?? body.payload) }; if (body.type === "implementation_sealed") payload = { submission: parseWebImplementationSubmission((body.payload as any)?.submission ?? body.payload) }; if (body.type === "repository_command") { const value = body.payload as any; if (!value || typeof value.request_id !== "string" || !value.command || typeof value.command.operation !== "string") throw new WebBridgeError("RELAY_EVENT_INVALID", "Repository command is invalid."); payload = { request_id: value.request_id, command: value.command }; } const event = await options.store.append(decodeURIComponent(eventMatch[1]!), principal.owner, body.type, payload, idempotency(request)); send(response, 201, event); return; }
      const localEventMatch = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/local-events$/);
      if (method === "GET" && localEventMatch) { const after = Number(url.searchParams.get("after") ?? 0); if (!Number.isSafeInteger(after) || after < 0) throw new WebBridgeError("RELAY_REQUEST_INVALID", "Event sequence is invalid."); const event = (await options.store.events(decodeURIComponent(localEventMatch[1]!), principal.owner, after)).map(toAuthoringEvent).find(Boolean) ?? null; send(response, 200, { event }); return; }
      const resultMatch = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/repository-results$/);
      if (method === "POST" && resultMatch) { await options.store.append(decodeURIComponent(resultMatch[1]!), principal.owner, "repository_command_result", await jsonBody(request), idempotency(request)); send(response, 201, { accepted: true }); return; }
      const clarificationMatch = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/clarifications$/);
      if (method === "POST" && clarificationMatch) { const body = await jsonBody(request) as any; if (typeof body?.text !== "string" || !body.text || body.text.length > 16_384) throw new WebBridgeError("RELAY_REQUEST_INVALID", "Clarification is invalid."); await options.store.append(decodeURIComponent(clarificationMatch[1]!), principal.owner, "user_clarification", { text: body.text }, idempotency(request)); send(response, 201, { accepted: true }); return; }
      const repositoryAction = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/repository\/(summary|tree|search|files)$/);
      if (method === "POST" && repositoryAction) { const body = await jsonBody(request) as any; const key = idempotency(request); const requestId = typeof body?.request_id === "string" ? body.request_id : `rpc-${key}`; const operation = repositoryAction[2] === "files" ? "read" : repositoryAction[2]; const command = operation === "summary" ? { operation } : operation === "tree" ? { operation, ...(body?.prefix ? { prefix: body.prefix } : {}), ...(body?.maximum_paths ? { maximum_paths: body.maximum_paths } : {}) } : operation === "search" ? { operation, query: body?.query, ...(body?.maximum_matches ? { maximum_matches: body.maximum_matches } : {}) } : { operation, paths: body?.paths }; const event = await options.store.append(decodeURIComponent(repositoryAction[1]!), principal.owner, "repository_command", { request_id: requestId, command }, key); send(response, 201, { request_id: requestId, event_sequence: event.sequence, status: "pending_local_result" }); return; }
      const repositoryResult = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/repository-results\/([^/]+)$/);
      if (method === "GET" && repositoryResult) { const requestId = decodeURIComponent(repositoryResult[2]!); const event = (await options.store.events(decodeURIComponent(repositoryResult[1]!), principal.owner, 0)).slice().reverse().find((item) => item.type === "repository_command_result" && (item.payload as any)?.request_id === requestId); send(response, 200, { result: event?.payload ?? null }); return; }
      const artifactMatch = url.pathname.match(/^\/v1\/jobs\/([^/]+)\/(contract|implementation)$/);
      if (method === "GET" && artifactMatch) { const type = artifactMatch[2] === "contract" ? "contract_sealed" : "implementation_sealed"; const event = (await options.store.events(decodeURIComponent(artifactMatch[1]!), principal.owner, 0)).slice().reverse().find((item) => item.type === type); const key = artifactMatch[2] === "contract" ? "envelope" : "submission"; send(response, 200, { [key]: event ? (event.payload as any)?.[key] ?? event.payload : null }); return; }
      const verdictMatch = url.pathname.match(/^\/v1\/final-reviews\/([^/]+)\/verdict$/);
      if (method === "GET" && verdictMatch) { const event = (await options.store.events(decodeURIComponent(verdictMatch[1]!), principal.owner, 0)).slice().reverse().find((item) => item.type === "web_verdict"); send(response, 200, { verdict: event ? (event.payload as any)?.verdict ?? event.payload : null }); return; }
      if (method === "POST" && verdictMatch) { const body = parseWebVerdictEnvelope(await jsonBody(request)); await options.store.append(decodeURIComponent(verdictMatch[1]!), principal.owner, "web_verdict", body, idempotency(request)); send(response, 201, { accepted: true }); return; }
      const evidenceMatch = url.pathname.match(/^\/v1\/final-reviews\/([^/]+)\/evidence$/);
      if (method === "POST" && evidenceMatch) { await options.store.append(decodeURIComponent(evidenceMatch[1]!), principal.owner, "final_review_evidence", await jsonBody(request), idempotency(request)); send(response, 201, { accepted: true }); return; }
      if (method === "GET" && evidenceMatch) { const event = (await options.store.events(decodeURIComponent(evidenceMatch[1]!), principal.owner, 0)).slice().reverse().find((item) => item.type === "final_review_evidence"); send(response, 200, { evidence: event?.payload ?? null }); return; }
      send(response, 404, { error: { code: "RELAY_ROUTE_NOT_FOUND", message: "Relay route was not found." } });
    } catch (error) {
      const code = error instanceof WebBridgeError ? error.code : "RELAY_OPERATIONAL_ERROR";
      const status = code === "RELAY_UNAUTHORIZED" ? 401 : code === "RELAY_FORBIDDEN" ? 403 : code.endsWith("_LIMIT") ? 413 : code.includes("CONFLICT") ? 409 : 400;
      send(response, status, { error: { code, message: error instanceof Error ? error.message : String(error) } });
    }
  });
}
