import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type { GitHubAttestationClient } from "../src/result-bundle/github-attestation.js";
import { FakeWebBridge } from "../src/web-bridge/fake-web-bridge.js";
import { createPendingFinalReview } from "../src/web-bridge/final-review-service.js";
import { materializeAndSubmitWebVerdict } from "../src/web-bridge/verdict-materializer.js";
import { WEB_BRIDGE_PROTOCOL_VERSION } from "../src/web-bridge/contracts.js";
import { createPhase6BundleFixture, TEST_BASE_COMMIT, TEST_PUBLISHED_COMMIT } from "./helpers/phase7-fixtures.js";

test("Result Bundle evidence reaches fake Web bridge and APPROVE returns only human merge authority", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wco-v03-final-review-")); const fixture = await createPhase6BundleFixture(root); const accepted = path.join(root, "accepted", "TEST-TASK", "1".repeat(64)); await mkdir(accepted, { recursive: true }); await writeFile(path.join(accepted, "acceptance.json"), JSON.stringify({ criteria: [{ id: "AC-1", description: "First criterion" }] })); const configPath = path.join(root, "config.json"); await writeFile(configPath, JSON.stringify({ config_version: "1.0", inbox: { poll_interval_ms: 1, stable_age_ms: 1, stable_observations: 1, maximum_candidates_per_scan: 1 }, repositories: { repo: { path: root, remote: "origin", expected_remote_urls: ["https://github.com/owner/repo"], fetch_policy: "never" } }, github_pull_request: { provider: "github.com", authentication: { mode: "https_token", token_environment_key: "WCO_GITHUB_TOKEN" } } })); const bridge = new FakeWebBridge(); const review = await createPendingFinalReview({ bridge, runId: fixture.receipt.run_id, stateDirectory: root }); assert.ok(bridge.finalReviewEvidence.get(review.job_id)?.entries); const githubClient: GitHubAttestationClient = { async getPullRequest(_owner, _repo, number) { return { number, state: "open", draft: true, merged: false, head: { ref: "codex/feature", sha: TEST_PUBLISHED_COMMIT, repo: { full_name: "owner/repo" } }, base: { ref: "main", sha: TEST_BASE_COMMIT, repo: { full_name: "owner/repo" } } } as any; } }; const result = await materializeAndSubmitWebVerdict({ envelope: { protocol_version: WEB_BRIDGE_PROTOCOL_VERSION, review_id: review.job_id, run_id: fixture.receipt.run_id, result_bundle_sha256: fixture.receipt.archive_sha256!, verdict: "APPROVE", summary: "Exact evidence satisfies the contract.", findings: [] }, stateDirectory: root, configPath, githubClient, now: () => new Date("2026-02-15T09:00:00.000Z") }); assert.equal(result.receipt.state, "APPROVED"); assert.equal(result.receipt.action, "ASK_USER_TO_MERGE"); });
