import test from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { advanceLocalWorker, completeLocalWorkerSession, localWorkerJobMode, readLocalWorkerSession, startLocalAuthoring } from "../src/web-bridge/local-worker.js";
import { FakeWebBridge } from "../src/web-bridge/fake-web-bridge.js";
import { WEB_BRIDGE_PROTOCOL_VERSION } from "../src/web-bridge/contracts.js";
import { withFinalReviewNotification } from "../src/tui/autopilot-web-bridge.js";
import { formatAutopilotOutcome, formatAutopilotStatus } from "../src/tui/autopilot-presenter.js";
import { commandPalette, parseInteractiveInput } from "../src/tui/slash-commands.js";
import type { AutopilotJobReceipt } from "../src/orchestration/autopilot-job.js";
const run = promisify(execFile);
async function repository(root: string): Promise<{ repo: string; base: string; remote: string }> { const remote = path.join(root, "remote.git"), repo = path.join(root, "repo"); await run("git", ["init", "--bare", remote]); await run("git", ["init", "-b", "main", repo]); await run("git", ["config", "user.name", "Test"], { cwd: repo }); await run("git", ["config", "user.email", "test@example.invalid"], { cwd: repo }); await writeFile(path.join(repo, "app.txt"), "before\n"); await writeFile(path.join(repo, "package.json"), JSON.stringify({ scripts: { test: "node --test" } })); await run("git", ["add", "."], { cwd: repo }); await run("git", ["commit", "-m", "base"], { cwd: repo }); await run("git", ["remote", "add", "origin", remote], { cwd: repo }); const base = (await run("git", ["rev-parse", "HEAD"], { cwd: repo })).stdout.trim(); return { repo, base, remote }; }
function trustedConfig(repo: string, remote: string): any { return { config_version: "1.0", inbox: { poll_interval_ms: 1, stable_age_ms: 1, stable_observations: 1, maximum_candidates_per_scan: 10 }, repositories: { repo: { path: repo, remote: "origin", expected_remote_urls: [remote], fetch_policy: "never" } }, runtime: { source: "bundled" }, verification: { allowed_executables: ["npm"], allowed_environment_keys: ["CI"], maximum_command_seconds: 60, maximum_output_bytes: 1_000_000, maximum_changed_files: 10, maximum_diff_lines: 1_000, allowed_generated_paths: [] }, publish: { identity: { name: "Test", email: "test@example.invalid" }, authentication: { mode: "none" } } }; }
function contract(jobId: string, base: string): any { return { protocol_version: WEB_BRIDGE_PROTOCOL_VERSION, job_id: jobId, repository: { repository_id: "repo", base_branch: "main", base_commit: base }, user_intent: "change app", title: "Change app", goal: "Replace app", non_goals: ["No unrelated change"], architecture_decisions: ["Keep format"], allowed_paths: ["app.txt"], forbidden_paths: [".git/**"], acceptance_criteria: [{ id: "AC-001", description: "app changed" }], verification_commands: [{ id: "test", executable: "npm", args: ["test"] }], risk_policy: { network_access: false, secrets_required: false, notes: [] }, delivery: { remote: "origin", base_branch: "main", branch_name: "codex/auto-user-flow", draft: true, auto_merge: false }, sources: [], implementation_strategy: ["replace app"], project_map_hints: ["app.txt"] }; }
test("V04-UX-001 /auto is explicit while plain goals remain PAIR-compatible", () => { assert.match(commandPalette(), /\/auto/); assert.deepEqual(parseInteractiveInput("/auto Fix the authentication race", { active: false, sealed: false }), { kind: "command", command: "/auto", args: "Fix the authentication race" }); assert.deepEqual(parseInteractiveInput("Fix the authentication race", { active: false, sealed: false }), { kind: "new", goal: "Fix the authentication race" }); });
test("V04-UX-002 AUTOPILOT mode reaches prepared contract without consuming Web implementation authority", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "wco-auto-ux-")); const { repo, base, remote } = await repository(root); const stateDirectory = path.join(root, "state"), configPath = path.join(root, "config.json"), config = trustedConfig(repo, remote); await writeFile(configPath, JSON.stringify(config)); const bridge = new FakeWebBridge(); try { let session = await startLocalAuthoring({ bridge, repository: { repository_id: "repo", base_branch: "main", base_commit: base }, goal: "change app", stateDirectory, mode: "AUTOPILOT" }); assert.equal(localWorkerJobMode(session), "AUTOPILOT"); assert.equal(bridge.authoringRequests.at(-1)?.orchestration_mode, "AUTOPILOT"); bridge.enqueue(session.job_id!, { sequence: 1, type: "contract_sealed", envelope: contract(session.job_id!, base) }); bridge.enqueue(session.job_id!, { sequence: 2, type: "implementation_sealed", submission: { protocol_version: WEB_BRIDGE_PROTOCOL_VERSION, job_id: session.job_id!, run_id: `wrong:${"f".repeat(64)}`, contract_only: false, summary: "must not be consumed by AUTOPILOT", operations: [], project_map: [], sources: [] } } as any); session = await advanceLocalWorker({ bridge, session, repositoryPath: repo, stateDirectory, configPath, config, stopAfterPrepared: true }); assert.equal(session.state, "PREPARED"); assert.equal(session.last_event_sequence, 1); assert.ok(session.run_id); assert.equal(session.web_pack_path, null); assert.equal(localWorkerJobMode((await readLocalWorkerSession(stateDirectory, "repo"))!), "AUTOPILOT"); await completeLocalWorkerSession({ session, stateDirectory }); assert.equal(session.state, "COMPLETED"); const next = await startLocalAuthoring({ bridge, repository: { repository_id: "repo", base_branch: "main", base_commit: base }, goal: "next pair task", stateDirectory }); assert.equal(localWorkerJobMode(next), "PAIR"); assert.equal(next.state, "AUTHORING"); } finally { await rm(root, { recursive: true, force: true }); } });
test("V04-UX-003 final-review browser notification is once-per-review and never authority", async () => { const bridge = new FakeWebBridge(); const verdict = { protocol_version: WEB_BRIDGE_PROTOCOL_VERSION, review_id: "review-1" } as any; bridge.submitVerdict("review-1", verdict); let notifications = 0; const wrapped = withFinalReviewNotification(bridge, async () => { notifications += 1; throw new Error("desktop browser unavailable"); }); assert.equal(await wrapped.waitForVerdict("review-1"), verdict); assert.equal(await wrapped.waitForVerdict("review-1"), verdict); assert.equal(notifications, 1); });
test("V04-UX-004 AUTOPILOT user presentation does not leak run/state/bundle internals", () => { const receipt = { schema_version: "2.0", mode: "AUTOPILOT", run_id: `task:${"a".repeat(64)}`, generation: 1, status: "READY_FOR_YOU", stage: "DONE", stage_attempts: { EXECUTE: 0, PUBLISH: 0, DRAFT_PR: 0, PACKAGE_RESULT: 0, WAIT_WEB: 0, REVISE: 0 }, next_retry_at: null, pending_review_job_id: null, web_review_rounds: 1, revision_rounds_completed: 0, terminal_action: "ASK_USER_TO_MERGE", reason: null, created_at: "2030-01-01T00:00:00.000Z", updated_at: "2030-01-01T00:00:00.000Z" } as AutopilotJobReceipt; const status = formatAutopilotStatus(receipt), outcome = formatAutopilotOutcome(receipt, "https://github.com/example/repo/pull/42"); assert.equal(status, "AUTOPILOT · READY_FOR_YOU"); assert.match(outcome, /READY FOR YOU/); assert.match(outcome, /pull\/42/); assert.doesNotMatch(`${status}\n${outcome}`, /run[_ -]?id|state-dir|Task Bundle|[a-f0-9]{64}/i); });
test("V04-UX-005 relay pending surfaces select newest work and reject invalid modes", async () => { const { RelayFileStore } = await import("../src/web-bridge/relay/file-store.js"); const { PersonalBearerAuthenticator } = await import("../src/web-bridge/relay/auth.js"); const { createRelayServer } = await import("../src/web-bridge/relay/server.js"); const { ActionRelayWebBridge } = await import("../src/web-bridge/action-relay-client.js"); const root = await mkdtemp(path.join(os.tmpdir(), "wco-auto-relay-latest-")), token = "t".repeat(40); const server = createRelayServer({ store: new RelayFileStore(path.join(root, "relay")), authenticator: new PersonalBearerAuthenticator([{ owner: "user", token }]) }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); const address = server.address(); assert.ok(address && typeof address === "object"); const relayUrl = `http://127.0.0.1:${address.port}`, client = new ActionRelayWebBridge({ relayUrl, token: async () => token }); try { const repo = { repository_id: "repo", base_branch: "main", base_commit: "a".repeat(40) }; const first = await client.createAuthoringJob({ owner: "ignored", repository: repo, user_intent: "first", ttl_seconds: 600, orchestration_mode: "PAIR" }, "first"); const second = await client.createAuthoringJob({ owner: "ignored", repository: repo, user_intent: "second", ttl_seconds: 600, orchestration_mode: "AUTOPILOT" }, "second"); assert.notEqual(first.job_id, second.job_id); const pending = await fetch(`${relayUrl}/v1/authoring/pending`, { headers: { Authorization: `Bearer ${token}` } }); assert.equal(pending.status, 200); const body = await pending.json() as any; assert.equal(body.job.identity.job_id, second.job_id); assert.equal(body.job.request.orchestration_mode, "AUTOPILOT"); assert.equal((await client.getConnectionStatus()).pending_author_job, second.job_id); const invalid = await fetch(`${relayUrl}/v1/authoring/jobs`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "Idempotency-Key": "invalid-mode" }, body: JSON.stringify({ owner: "ignored", repository: repo, user_intent: "invalid", ttl_seconds: 600, orchestration_mode: "UNGUARDED" }) }); assert.equal(invalid.status, 400); assert.match(await invalid.text(), /orchestration_mode/); assert.equal((await client.getConnectionStatus()).pending_author_job, second.job_id); } finally { await new Promise<void>((resolve) => server.close(() => resolve())); await rm(root, { recursive: true, force: true }); } });
