import { access } from "node:fs/promises";
import readline from "node:readline/promises";
import { CodexSdkAgentClient } from "../agent/codex-sdk-client.js";
import { resolveCodexRuntime } from "../runtime/codex-runtime.js";
import { resolveGitHubToken } from "./credential-provider.js";
import { performFirstRunSetup } from "./first-run.js";

export async function runSetupCommand(args: string[], cwd = process.cwd()): Promise<number> { let yes = false, overwrite = false, configPath: string | undefined, stateDirectory: string | undefined; for (let i = 0; i < args.length; i++) { const arg = args[i]!; if (arg === "--yes") yes = true; else if (arg === "--force") overwrite = true; else if (arg === "--config" || arg === "--state-dir") { const value = args[++i]; if (!value) return 2; if (arg === "--config") configPath = value; else stateDirectory = value; } else { process.stderr.write("Usage: wco setup [--yes] [--force] [--config <path>] [--state-dir <path>]\n"); return 2; } }
  if (!yes) { if (!process.stdin.isTTY || !process.stdout.isTTY) { process.stderr.write("Setup needs confirmation. Re-run with --yes for non-interactive setup.\n"); return 2; } const io = readline.createInterface({ input: process.stdin, output: process.stdout }); try { const answer = await io.question("Set up WCO for the current Git repository? [Y/n] "); if (answer && !/^y(es)?$/i.test(answer)) { process.stdout.write("Setup cancelled.\n"); return 1; } } finally { io.close(); } }
  try { const result = await performFirstRunSetup({ cwd, ...(configPath ? { configPath } : {}), ...(stateDirectory ? { stateDirectory } : {}), overwrite }); const checks: Array<[string, string]> = [["Git repository", result.repository.root], ["Remote", result.repository.remote_url], ["Base branch", result.repository.base_branch], ["Project", result.project.kinds.join(", ") || "unknown"]]; let codex = "unavailable"; try { const runtime = await resolveCodexRuntime(result.config.runtime, result.paths.state); await new CodexSdkAgentClient(runtime).checkAvailability(); codex = `authenticated (${runtime.package_version})`; } catch { /* reported below */ } checks.push(["Codex", codex]); let github = "not configured"; if (result.config.github_pull_request) { try { await resolveGitHubToken(result.config.github_pull_request.authentication); github = "gh authenticated"; } catch { github = "authentication unavailable"; } } checks.push(["GitHub", github]); process.stdout.write(`\nWeb Codex Orchestrator v0.3 setup\n\n${checks.map(([label, value]) => `✓ ${label.padEnd(16)} ${value}`).join("\n")}\n\nConfig: ${result.paths.config}\nState:  ${result.paths.state}\n`); if (codex === "unavailable" || github === "authentication unavailable") { process.stdout.write("\nSetup was saved, but a credential check needs attention. Run `wco doctor`.\n"); return 1; } return 0; } catch (error) { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\nNo repository files or remote resources were changed.\n`); return 1; }
}
