import { WebBridgeError, parseWebContractEnvelope, parseWebImplementationSubmission, parseWebVerdictEnvelope, type AuthoringEvent, type BridgeConnectionStatus, type BridgeJobIdentity, type FinalReviewRequest, type RepositoryCommandResult, type WebContractEnvelope, type WebImplementationSubmission, type WebVerdictEnvelope } from "./contracts.js";
import type { AuthoringJobRequest, WebBridge } from "./web-bridge.js";

export interface RelayClientOptions { relayUrl: string; token: () => Promise<string>; timeoutMs?: number; maximumResponseBytes?: number; fetchImpl?: typeof fetch; onRequest?: (metrics: { method: string; route: string; request_bytes: number; response_bytes: number; duration_ms: number }) => void; }
function safeBase(value: string): URL { const url = new URL(value); if (url.username || url.password || url.hash || url.search || url.protocol !== "https:" && !(url.protocol === "http:" && ["127.0.0.1", "localhost", "::1"].includes(url.hostname))) throw new WebBridgeError("WEB_RELAY_URL_UNSAFE", "Relay URL must be HTTPS or loopback HTTP without credentials/query/fragment."); return url; }
async function boundedBody(response: Response, maximum: number): Promise<Buffer> { if (!response.body) return Buffer.alloc(0); const reader = response.body.getReader(); const chunks: Buffer[] = []; let total = 0; try { while (true) { const item = await reader.read(); if (item.done) break; const chunk = Buffer.from(item.value); total += chunk.length; if (total > maximum) { await reader.cancel(); throw new WebBridgeError("WEB_RELAY_RESPONSE_LIMIT", "Relay response exceeded its byte bound."); } chunks.push(chunk); } } finally { reader.releaseLock(); } return Buffer.concat(chunks, total); }

export class ActionRelayWebBridge implements WebBridge {
  private readonly base: URL;
  private readonly timeout: number;
  private readonly maximum: number;
  private readonly fetcher: typeof fetch;
  constructor(private readonly options: RelayClientOptions) { this.base = safeBase(options.relayUrl); this.timeout = options.timeoutMs ?? 10_000; this.maximum = options.maximumResponseBytes ?? 2_097_152; this.fetcher = options.fetchImpl ?? fetch; }
  private async request(method: string, route: string, body?: unknown, idempotencyKey?: string): Promise<unknown> { const token = await this.options.token(); if (!token || token.length > 4096 || /[\r\n\0]/.test(token)) throw new WebBridgeError("WEB_RELAY_AUTH_UNAVAILABLE", "Relay credential is unavailable."); const url = new URL(route, this.base); if (url.origin !== this.base.origin) throw new WebBridgeError("WEB_RELAY_URL_UNSAFE", "Relay route escaped its configured origin."); const encoded = body === undefined ? undefined : JSON.stringify(body); if (encoded && Buffer.byteLength(encoded) > 98_304) throw new WebBridgeError("WEB_RELAY_REQUEST_LIMIT", "Relay request exceeded the GPT Action transport bound."); const started = performance.now(); let response: Response; try { response = await this.fetcher(url, { method, redirect: "error", headers: { Authorization: `Bearer ${token}`, Accept: "application/json", ...(body === undefined ? {} : { "Content-Type": "application/json" }), ...(idempotencyKey ? { "Idempotency-Key": idempotencyKey } : {}) }, ...(encoded === undefined ? {} : { body: encoded }), signal: AbortSignal.timeout(this.timeout) }); } catch { throw new WebBridgeError("WEB_RELAY_RPC_TIMEOUT", "Relay request failed or timed out. No repository files were changed."); } const length = Number(response.headers.get("content-length") ?? 0); if (length > this.maximum) throw new WebBridgeError("WEB_RELAY_RESPONSE_LIMIT", "Relay response exceeded its byte bound."); const bytes = await boundedBody(response, this.maximum); this.options.onRequest?.({ method, route, request_bytes: encoded ? Buffer.byteLength(encoded) : 0, response_bytes: bytes.byteLength, duration_ms: Math.max(0, performance.now() - started) }); let parsed: unknown; try { parsed = bytes.length ? JSON.parse(bytes.toString("utf8")) : null; } catch { throw new WebBridgeError("WEB_RELAY_RESPONSE_INVALID", "Relay response was not valid JSON."); } if (!response.ok) throw new WebBridgeError(`WEB_RELAY_HTTP_${response.status}`, "Relay rejected the request. No WCO authority transition was made."); return parsed; }
  async createAuthoringJob(request: AuthoringJobRequest, key: string): Promise<BridgeJobIdentity> { return await this.request("POST", "/v1/authoring/jobs", request, key) as BridgeJobIdentity; }
  async waitForAuthoringEvent(jobId: string, afterSequence: number): Promise<AuthoringEvent | null> { const value = await this.request("GET", `/v1/jobs/${encodeURIComponent(jobId)}/local-events?after=${afterSequence}`) as { event?: AuthoringEvent | null }; return value.event ?? null; }
  async submitRepositoryCommandResult(jobId: string, result: RepositoryCommandResult, key: string): Promise<void> { await this.request("POST", `/v1/jobs/${encodeURIComponent(jobId)}/repository-results`, result, key); }
  async submitClarification(jobId: string, text: string, key: string): Promise<void> { await this.request("POST", `/v1/jobs/${encodeURIComponent(jobId)}/clarifications`, { text }, key); }
  async receiveSealedContract(jobId: string): Promise<WebContractEnvelope | null> { const value = await this.request("GET", `/v1/jobs/${encodeURIComponent(jobId)}/contract`) as { envelope?: unknown }; return value.envelope ? parseWebContractEnvelope(value.envelope) : null; }
  async receiveWebImplementation(jobId: string): Promise<WebImplementationSubmission | null> { const value = await this.request("GET", `/v1/jobs/${encodeURIComponent(jobId)}/implementation`) as { submission?: unknown }; return value.submission ? parseWebImplementationSubmission(value.submission) : null; }
  async createFinalReviewJob(request: FinalReviewRequest, key: string): Promise<BridgeJobIdentity> { return await this.request("POST", "/v1/final-reviews", request, key) as BridgeJobIdentity; }
  async submitFinalReviewEvidence(reviewId: string, evidence: Record<string, unknown>, key: string): Promise<void> { await this.request("POST", `/v1/final-reviews/${encodeURIComponent(reviewId)}/evidence`, evidence, key); }
  async waitForVerdict(reviewId: string): Promise<WebVerdictEnvelope | null> { const value = await this.request("GET", `/v1/final-reviews/${encodeURIComponent(reviewId)}/verdict`) as { verdict?: unknown }; return value.verdict ? parseWebVerdictEnvelope(value.verdict) : null; }
  async getConnectionStatus(): Promise<BridgeConnectionStatus> { return await this.request("GET", "/v1/status") as BridgeConnectionStatus; }
}
