import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import yazl from "yazl";
import { WebBridgeError } from "./contracts.js";

export interface BridgeZipEntry { path: string; content: Buffer; }
function safe(value: string): void { if (!value || value.includes("\\") || value.includes("\0") || value.startsWith("/") || /^[A-Za-z]:/.test(value) || value.split("/").some((part) => !part || part === "." || part === "..") || value === ".git" || value.startsWith(".git/")) throw new WebBridgeError("WEB_ARTIFACT_PATH_UNSAFE", `Unsafe archive path '${value}'.`); }
async function fileHash(file: string): Promise<string> { const hash = crypto.createHash("sha256"); for await (const chunk of fs.createReadStream(file)) hash.update(chunk as Buffer); return hash.digest("hex"); }
export async function buildWebBridgeZip(entries: BridgeZipEntry[], outputDirectory: string, filename: string, limits: { maximumEntries: number; maximumArchiveBytes: number; maximumUncompressedBytes: number }): Promise<{ archivePath: string; sha256: string; sizeBytes: number }> { if (entries.length > limits.maximumEntries) throw new WebBridgeError("WEB_ARTIFACT_ENTRY_LIMIT", "Archive entry count exceeds its bound."); let total = 0; const seen = new Set<string>(); for (const entry of entries) { safe(entry.path); const key = entry.path.normalize("NFC").toLowerCase(); if (seen.has(key)) throw new WebBridgeError("WEB_ARTIFACT_PATH_COLLISION", "Archive paths collide."); seen.add(key); total += entry.content.length; } if (total > limits.maximumUncompressedBytes) throw new WebBridgeError("WEB_ARTIFACT_SIZE_LIMIT", "Archive uncompressed bytes exceed the bound."); await fs.promises.mkdir(outputDirectory, { recursive: true, mode: 0o700 }); const target = path.join(outputDirectory, filename), temporary = `${target}.tmp-${process.pid}-${crypto.randomUUID()}`; await new Promise<void>((resolve, reject) => { const zip = new yazl.ZipFile(); const output = fs.createWriteStream(temporary, { flags: "wx", mode: 0o600 }); output.once("error", reject); output.once("close", resolve); zip.outputStream.once("error", reject); zip.outputStream.pipe(output); for (const entry of [...entries].sort((a, b) => a.path.localeCompare(b.path))) zip.addBuffer(entry.content, entry.path, { mtime: new Date(1980, 0, 1), mode: 0o100644, compress: true }); zip.end(); }); const size = (await fs.promises.stat(temporary)).size; if (size > limits.maximumArchiveBytes) { await fs.promises.unlink(temporary); throw new WebBridgeError("WEB_ARTIFACT_SIZE_LIMIT", "Archive bytes exceed the bound."); } const digest = await fileHash(temporary); try { await fs.promises.link(temporary, target); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST" || (await fs.promises.stat(target)).size !== size || await fileHash(target) !== digest) { await fs.promises.unlink(temporary).catch(() => undefined); throw new WebBridgeError("WEB_ARTIFACT_REPLAY_CONFLICT", "Existing archive differs from deterministic replay."); } } finally { await fs.promises.unlink(temporary).catch(() => undefined); } return { archivePath: target, sha256: digest, sizeBytes: size }; }
