import crypto from "node:crypto";
import { realpath } from "node:fs/promises";
import { spawnBounded, spawnBoundedBinary, type SpawnBounded, type SpawnBoundedBinary } from "../runtime/spawn-bounded.js";
import { assertRepositoryRelativePath } from "../web-authority/pack-reader.js";
import { WebBridgeError, type RepositoryBinding, type RepositoryCommand } from "./contracts.js";
import { ReadCoverageStore, type ReadCoverageReceipt } from "./read-coverage-store.js";

export interface RepoReadLimits { maximum_paths: number; maximum_query_length: number; maximum_matches: number; maximum_read_files: number; maximum_file_bytes: number; maximum_total_bytes: number; timeout_ms: number; }
const DEFAULT_LIMITS: RepoReadLimits = { maximum_paths: 5_000, maximum_query_length: 256, maximum_matches: 500, maximum_read_files: 32, maximum_file_bytes: 1_048_576, maximum_total_bytes: 4_194_304, timeout_ms: 5_000 };
const SENSITIVE = [/(^|\/)\.env($|\.)/i, /(^|\/)[^/]*\.(pem|key)$/i, /(^|\/)id_rsa[^/]*$/i, /(^|\/)(credentials|secrets?)[^/]*$/i, /(^|\/)\.git(\/|$)/i];
function denySensitive(value: string): void { assertRepositoryRelativePath(value); if (SENSITIVE.some((pattern) => pattern.test(value))) throw new WebBridgeError("WEB_REPOSITORY_PATH_SENSITIVE", `Repository path '${value}' is denied by sensitive-path policy.`); }
function environment(): Record<string, string> { const result: Record<string, string> = { GIT_CONFIG_NOSYSTEM: "1", GIT_TERMINAL_PROMPT: "0", GIT_OPTIONAL_LOCKS: "0", LC_ALL: "C" }; for (const key of ["PATH", "Path", "PATHEXT", "SYSTEMROOT", "SystemRoot"]) if (process.env[key]) result[key] = process.env[key]!; return result; }
function failed(result: { exitCode: number | null; timedOut: boolean; cancelled: boolean; stdoutTruncated: boolean; stderrTruncated: boolean; spawnError?: unknown }): boolean { return Boolean(result.spawnError || result.timedOut || result.cancelled || result.stdoutTruncated || result.stderrTruncated || result.exitCode !== 0); }

export class ExactRepositoryReadService {
  private readonly limits: RepoReadLimits;
  constructor(private readonly repositoryRoot: string, private readonly binding: RepositoryBinding, private readonly coverage: ReadCoverageStore, limits: Partial<RepoReadLimits> = {}, private readonly runText: SpawnBounded = spawnBounded, private readonly runBinary: SpawnBoundedBinary = spawnBoundedBinary) { this.limits = { ...DEFAULT_LIMITS, ...limits }; if (!/^[a-f0-9]{40}$/.test(binding.base_commit)) throw new WebBridgeError("WEB_REPOSITORY_BINDING_INVALID", "Base commit must be an exact lowercase Git object ID."); }
  private async text(args: string[], maximum: number): Promise<string> { const result = await this.runText({ executable: "git", args: ["-c", "core.hooksPath=/dev/null", ...args], cwd: await realpath(this.repositoryRoot), environment: environment(), timeoutMs: this.limits.timeout_ms, stdoutMaxBytes: maximum, stderrMaxBytes: 8_192, shell: false }); if (failed(result)) throw new WebBridgeError("WEB_REPOSITORY_READ_FAILED", "Bounded exact Git read failed."); return result.stdout; }
  private async binary(args: string[], maximum: number): Promise<Buffer> { const result = await this.runBinary({ executable: "git", args: ["-c", "core.hooksPath=/dev/null", ...args], cwd: await realpath(this.repositoryRoot), environment: environment(), timeoutMs: this.limits.timeout_ms, stdoutMaxBytes: maximum, stderrMaxBytes: 8_192, shell: false }); if (failed(result)) throw new WebBridgeError(result.stdoutTruncated ? "WEB_REPOSITORY_FILE_TOO_LARGE" : "WEB_REPOSITORY_READ_FAILED", "Bounded exact Git object read failed."); return result.stdout; }
  async verifyBinding(): Promise<void> { const head = (await this.text(["rev-parse", "--verify", `${this.binding.base_commit}^{commit}`], 128)).trim(); if (head !== this.binding.base_commit) throw new WebBridgeError("WEB_REPOSITORY_BINDING_DRIFT", "Exact base commit could not be re-attested."); }
  async summary(): Promise<{ repository_id: string; base_branch: string; base_commit: string; tree_sha: string }> { await this.verifyBinding(); const tree_sha = (await this.text(["rev-parse", `${this.binding.base_commit}^{tree}`], 128)).trim(); return { ...this.binding, tree_sha }; }
  async tree(prefix = "", maximumPaths = this.limits.maximum_paths): Promise<{ paths: string[]; truncated: boolean }> { await this.verifyBinding(); if (prefix) denySensitive(prefix); const maximum = Math.min(Math.max(1, maximumPaths), this.limits.maximum_paths); const args = ["ls-tree", "-r", "-z", "--name-only", this.binding.base_commit, ...(prefix ? ["--", prefix] : [])]; const raw = await this.binary(args, Math.min(this.limits.maximum_total_bytes, 8_388_608)); const all = raw.toString("utf8").split("\0").filter(Boolean).filter((item) => !SENSITIVE.some((pattern) => pattern.test(item))); return { paths: all.slice(0, maximum), truncated: all.length > maximum }; }
  async search(query: string, maximumMatches = this.limits.maximum_matches): Promise<{ matches: string[]; truncated: boolean }> { await this.verifyBinding(); if (!query || query.length > this.limits.maximum_query_length || /[\r\n\0]/.test(query)) throw new WebBridgeError("WEB_REPOSITORY_QUERY_INVALID", "Search query is invalid or exceeds its bound."); const maximum = Math.min(Math.max(1, maximumMatches), this.limits.maximum_matches); const result = await this.runText({ executable: "git", args: ["-c", "core.hooksPath=/dev/null", "grep", "-l", "-I", "-F", "-e", query, this.binding.base_commit, "--"], cwd: await realpath(this.repositoryRoot), environment: environment(), timeoutMs: this.limits.timeout_ms, stdoutMaxBytes: this.limits.maximum_total_bytes, stderrMaxBytes: 8_192, shell: false }); if (result.exitCode === 1 && !result.spawnError && !result.timedOut) return { matches: [], truncated: false }; if (failed(result)) throw new WebBridgeError("WEB_REPOSITORY_READ_FAILED", "Bounded exact Git search failed."); const prefix = `${this.binding.base_commit}:`; const all = result.stdout.split("\n").filter(Boolean).map((line) => line.startsWith(prefix) ? line.slice(prefix.length) : "").filter((location) => location && !SENSITIVE.some((pattern) => pattern.test(location))); return { matches: all.slice(0, maximum), truncated: all.length > maximum };
  }
  async read(jobId: string, requestId: string, paths: string[], now = () => new Date()): Promise<{ files: Array<{ path: string; content_base64: string; content_sha256: string; blob_sha: string; size_bytes: number }> }> { await this.verifyBinding(); if (paths.length < 1 || paths.length > this.limits.maximum_read_files || new Set(paths).size !== paths.length) throw new WebBridgeError("WEB_REPOSITORY_READ_LIMIT", "File read request exceeds bounds or contains duplicates."); let total = 0; const files = []; for (const item of paths) { denySensitive(item); const content = await this.binary(["show", `${this.binding.base_commit}:${item}`], this.limits.maximum_file_bytes + 1); if (content.byteLength > this.limits.maximum_file_bytes || total + content.byteLength > this.limits.maximum_total_bytes) throw new WebBridgeError("WEB_REPOSITORY_READ_LIMIT", "File read response exceeds byte bounds."); total += content.byteLength; const blob_sha = (await this.text(["rev-parse", `${this.binding.base_commit}:${item}`], 128)).trim(); const content_sha256 = crypto.createHash("sha256").update(content).digest("hex"); const receipt: ReadCoverageReceipt = { schema_version: "1.0", job_id: jobId, request_id: requestId, base_commit: this.binding.base_commit, path: item, blob_sha, content_sha256, start_byte: 0, end_byte_exclusive: content.byteLength, total_bytes: content.byteLength, observed_at: now().toISOString() }; await this.coverage.append(receipt); files.push({ path: item, content_base64: content.toString("base64"), content_sha256, blob_sha, size_bytes: content.byteLength }); } return { files }; }
  async execute(jobId: string, requestId: string, command: RepositoryCommand): Promise<unknown> { if (command.operation === "summary") return await this.summary(); if (command.operation === "tree") return await this.tree(command.prefix ?? "", command.maximum_paths); if (command.operation === "search") return await this.search(command.query, command.maximum_matches); return await this.read(jobId, requestId, command.paths); }
}
