import { spawn } from "node:child_process";
import { loadTrustedConfig } from "../config/config-loader.js";
import { resolveWcoPaths } from "../setup/default-paths.js";
import { createConfiguredWebBridge } from "./bridge-factory.js";
import { PersonalBearerAuthenticator } from "./relay/auth.js";
import { RelayFileStore } from "./relay/file-store.js";
import { createRelayServer } from "./relay/server.js";

function openBrowser(urlValue: string): void { const url = new URL(urlValue); if (url.protocol !== "https:") throw new Error("WEB_GPT_URL_UNSAFE: GPT URL must use HTTPS."); const command = process.platform === "win32" ? "explorer.exe" : process.platform === "darwin" ? "open" : "xdg-open"; const child = spawn(command, [url.href], { detached: true, stdio: "ignore", shell: false }); child.unref(); }
export async function runWebCommand(args: string[]): Promise<number> { const operation = args[0] ?? "status"; if (operation === "relay") { const token = process.env.WCO_RELAY_TOKEN, owner = process.env.WCO_RELAY_OWNER ?? "local"; if (!token) { process.stderr.write("WEB_RELAY_AUTH_UNAVAILABLE: set WCO_RELAY_TOKEN (at least 32 characters).\n"); return 1; } const paths = resolveWcoPaths({}); const port = Number(process.env.WCO_RELAY_PORT ?? 8787); if (!Number.isSafeInteger(port) || port < 1 || port > 65535) return 2; const server = createRelayServer({ store: new RelayFileStore(`${paths.bridge}/relay`), authenticator: new PersonalBearerAuthenticator([{ owner, token }]) }); await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(port, "127.0.0.1", () => resolve()); }); process.stdout.write(`WCO relay listening on http://127.0.0.1:${port}\n`); return await new Promise<number>((resolve) => { const stop = () => server.close(() => resolve(0)); process.once("SIGINT", stop); process.once("SIGTERM", stop); }); }
  if (!["status", "open", "connect", "disconnect"].includes(operation) || args.length > 1) { process.stderr.write("Usage: wco web [status|open|connect|disconnect|relay]\n"); return 2; } const paths = resolveWcoPaths({}); try { const config = await loadTrustedConfig(paths.config); const bridge = createConfiguredWebBridge(config, paths.bridge); if (operation === "open") { if (!config.web_bridge?.gpt_url) throw new Error("WEB_GPT_NOT_CONFIGURED: set web_bridge.gpt_url in trusted config."); openBrowser(config.web_bridge.gpt_url); process.stdout.write("Opened the configured GPT URL. Connection is not assumed; use `wco web status` to verify it.\n"); return 0; } if (operation === "disconnect") { process.stdout.write("WCO did not delete environment/OAuth credentials. Revoke or remove the configured relay credential, then verify with `wco web status`.\n"); return 0; } const status = await bridge.getConnectionStatus(); process.stdout.write(`Web Architect GPT     ${config.web_bridge?.gpt_url ? "configured" : "missing"}\nRelay                 ${status.connected ? "connected" : "offline"}\nAccount               ${status.account ?? "missing"}\nPending author task   ${status.pending_author_job ?? "none"}\nPending final review  ${status.pending_final_review ?? "none"}\n`); return status.connected ? 0 : 1; } catch (error) { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\nNo repository files or workflow authority were changed. Try: wco web status\n`); return 1; } }
