import { lstat, readFile, readdir, realpath, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import type { TrustedConfig } from "../config/contracts.js";
import { inventoryOwnedResources, type UninstallInventory } from "./inventory.js";
import { spawnBounded } from "../runtime/spawn-bounded.js";

function contains(parent: string, child: string): boolean { const relative = path.relative(parent, child); return relative === "" || relative !== ".." && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative); }
interface ManagedWorktree { repository: string; worktree: string; }
async function managedWorktrees(home: string, config?: TrustedConfig): Promise<ManagedWorktree[]> { if (!config) return []; const runs = path.join(home, "state", "runs"); let taskNames: string[]; try { taskNames = await readdir(runs); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } if (taskNames.length > 4096) throw new Error("UNINSTALL_INVENTORY_LIMIT: run registry exceeds the safe bound."); const values = new Map<string, ManagedWorktree>(); for (const task of taskNames) { const taskPath = path.join(runs, task); const taskStat = await lstat(taskPath); if (!taskStat.isDirectory() || taskStat.isSymbolicLink()) throw new Error("UNINSTALL_STATE_UNSAFE: run registry contains an unsafe entry."); const archives = await readdir(taskPath); if (archives.length > 4096) throw new Error("UNINSTALL_INVENTORY_LIMIT: task run registry exceeds the safe bound."); for (const archive of archives) { const receiptPath = path.join(taskPath, archive, "run.json"); let bytes: Buffer; try { const stat = await lstat(receiptPath); if (!stat.isFile() || stat.isSymbolicLink() || stat.size > 1_048_576) throw new Error("unsafe"); bytes = await readFile(receiptPath); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") continue; throw new Error("UNINSTALL_STATE_UNSAFE: cannot attest a managed worktree receipt."); } const receipt = JSON.parse(bytes.toString("utf8")) as { repository_id?: unknown; worktree_path?: unknown }; if (typeof receipt.repository_id !== "string" || typeof receipt.worktree_path !== "string") throw new Error("UNINSTALL_STATE_UNSAFE: managed worktree receipt is invalid."); const registered = config.repositories[receipt.repository_id]; if (!registered) throw new Error("UNINSTALL_STATE_UNSAFE: managed worktree repository is no longer registered."); const repository = await realpath(registered.path), worktree = path.resolve(receipt.worktree_path); if (worktree === repository) throw new Error("UNINSTALL_REPOSITORY_PROTECTED: a run receipt points at the original repository."); values.set(worktree, { repository, worktree }); } } return [...values.values()]; }
function gitEnvironment(): Record<string, string> { return { PATH: process.env.PATH ?? "", GIT_TERMINAL_PROMPT: "0", GIT_OPTIONAL_LOCKS: "0" }; }
async function attestCleanWorktrees(values: ManagedWorktree[]): Promise<void> { for (const value of values) { let stat; try { stat = await lstat(value.worktree); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") continue; throw error; } if (!stat.isDirectory() || stat.isSymbolicLink() || await realpath(value.worktree) !== value.worktree) throw new Error("UNINSTALL_WORKTREE_UNSAFE: managed worktree is not canonical."); const status = await spawnBounded({ executable: "git", args: ["-c", "core.hooksPath=/dev/null", "-C", value.worktree, "status", "--porcelain=v1", "-z", "--untracked-files=all"], environment: gitEnvironment(), timeoutMs: 5_000, stdoutMaxBytes: 1_048_576, stderrMaxBytes: 65_536, shell: false }); if (status.spawnError || status.timedOut || status.exitCode !== 0 || status.stdoutTruncated || status.stdout.length) throw new Error("UNINSTALL_DIRTY_WORKTREE: a managed worktree is dirty or cannot be attested; it was preserved."); const listing = await spawnBounded({ executable: "git", args: ["-c", "core.hooksPath=/dev/null", "-C", value.repository, "worktree", "list", "--porcelain"], environment: gitEnvironment(), timeoutMs: 5_000, stdoutMaxBytes: 1_048_576, stderrMaxBytes: 65_536, shell: false }); if (listing.spawnError || listing.timedOut || listing.exitCode !== 0 || !listing.stdout.split("\n").includes(`worktree ${value.worktree}`)) throw new Error("UNINSTALL_WORKTREE_UNSAFE: managed worktree is not registered by its original repository."); } }
async function removeCleanWorktrees(values: ManagedWorktree[]): Promise<void> { for (const value of values) { try { await lstat(value.worktree); } catch { continue; } const removed = await spawnBounded({ executable: "git", args: ["-c", "core.hooksPath=/dev/null", "-C", value.repository, "worktree", "remove", value.worktree], environment: gitEnvironment(), timeoutMs: 15_000, stdoutMaxBytes: 65_536, stderrMaxBytes: 65_536, shell: false }); if (removed.spawnError || removed.timedOut || removed.exitCode !== 0) throw new Error("UNINSTALL_WORKTREE_REMOVE_FAILED: a clean managed worktree could not be removed; remaining resources were preserved."); } }
export async function purgeWcoHome(options: { home: string; config?: TrustedConfig; dryRun?: boolean }): Promise<UninstallInventory> { const inventory = await inventoryOwnedResources(options.home, options.config); const home = inventory.home; const parsed = path.parse(home); const userHome = path.resolve(os.homedir()); if (home === parsed.root || home === userHome || home.length < parsed.root.length + 4) throw new Error("UNINSTALL_HOME_UNSAFE: refusing to remove a broad filesystem location."); for (const repository of inventory.protected_repositories) if (contains(home, repository) || contains(repository, home)) throw new Error("UNINSTALL_REPOSITORY_PROTECTED: WCO home overlaps a registered source repository; nothing was removed."); const worktrees = await managedWorktrees(home, options.config); if (options.dryRun) return { ...inventory, warnings: worktrees.length ? [`${worktrees.length} managed worktree(s) will be removed only after a clean exact re-attestation.`] : [] }; const before = await lstat(home); if (before.isSymbolicLink() || !before.isDirectory() || await realpath(home) !== home) throw new Error("UNINSTALL_HOME_UNSAFE: WCO home changed before purge."); await attestCleanWorktrees(worktrees); await removeCleanWorktrees(worktrees); await rm(home, { recursive: true, force: false, maxRetries: 2 }); return inventory; }
